# -------- Generated by configure -----------
#
# Updated for Stella 7.0. Two things matter here:
#
#  * IMAGE_SUPPORT is what 7.0 calls the old PNG_SUPPORT. Without it the ROM
#    launcher compiles and runs but shows "Image loading not supported" where
#    the game snapshot should be. Nothing fails, the feature is simply absent.
#  * 7.0 moved its tree: src/unix -> src/os/unix, and third-party code now
#    lives under src/lib. The paths below follow that.

CXX := arm-none-linux-gnueabihf-c++
CXXFLAGS := $(CFLAGS_HP)
LD :=  arm-none-linux-gnueabihf-c++
LDFLAGS := -march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4
LIBS +=  -L$(BUILDDIR)/lib -lSDL2 -lpng -lz -pthread
RANLIB := arm-none-linux-gnueabihf-ranlib
INSTALL := install
AR := arm-none-linux-gnueabihf-ar cru
MKDIR := mkdir -p
ECHO := printf
CAT := cat
RM := rm -f
RM_REC := rm -f -r
ZIP := zip -q
CP := cp
WINDOWSPATH=
STRIP := arm-none-linux-gnueabihfstrip
BINARY_LOADER := qemu-arm -cpu cortex-a7 -L $(ROOTFSDIR)

MODULES +=  src/os/unix src/os/unix/r77 src/gui src/lib/tinyexif src/lib/sqlite
MODULE_DIRS +=
EXEEXT :=

PREFIX := /usr/local
BINDIR := /usr/local/bin
DOCDIR := /usr/local/share/doc/stella
DATADIR := /usr/local/share
PROFILE :=

HAVE_GCC = 1

INCLUDES += -I$(BUILDDIR)/include -I/$(BUILDDIR)/include/SDL2 -Isrc/emucore -Isrc/common -Isrc/common/tv_filters -Isrc/gui -Isrc/emucore/tia -Isrc/emucore/tia/frame-manager -Isrc/emucore/elf -Isrc/os/unix -Isrc/os/unix/r77 -Isrc/lib/json -Isrc/common/repository/sqlite -Isrc/lib/sqlite -Isrc/lib/nanojpeg -Isrc/lib/tinyexif -I/usr/local/include/SDL2 -D_THREAD_SAFE
OBJS +=
DEFINES +=  -DUNIX -DBSPF_UNIX -DRETRON77 -DSOUND_SUPPORT -DJOYSTICK_SUPPORT -DSDL_SUPPORT -DGUI_SUPPORT -DIMAGE_SUPPORT -DZIP_SUPPORT
LDFLAGS +=

CXX_UPDATE_DEP_FLAG = -MMD -MF "$(*D)/$(DEPDIR)/$(*F).d" -MQ "$@" -MP
